sources:
  - name: StakeStarTestnet
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/arsoba/stakestar-test
  - name: StakeStarMainnet
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/arsoba/stakestar-test

documents:
  - ./queries/*.graphql
