name: 'Publish subgraph-client GitHub Package'

on:
  release:
    types: [created]

jobs:
  publish-github-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://npm.pkg.github.com/
      - run: cd ./subgraph-client && yarn
      - run: cd ./subgraph-client && yarn build:graphclient
      - run: cd ./subgraph-client && yarn build:package
      - run: cd ./subgraph-client && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
